name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          libffi-dev \
          libssl-dev \
          libjpeg-dev \
          zlib1g-dev \
          autoconf \
          libtool \
          pkg-config \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          openjdk-17-jdk \
          unzip \
          zip
    
    - name: Install buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython
    
    - name: Build APK
      run: |
        yes | buildozer android debug
      timeout-minutes: 120
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: T0Trading-APK
        path: bin/*.apk
        if-no-files-found: error
